Support webpack 4.0 tapable api
lettertwo/appcache-webpack-plugin pull request #24
Opened 2018-04-03 19:09 UTC by ccorcos

2018-04-03 19:36 UTC, lettertwo requested changes
Hi @ccorcos, thanks for the PR!

I made a couple of notes about changes i'd like before merging this. If you have the time, I would greatly appreciate it!

2018-04-03 19:36 UTC, lettertwo commented on src/index.js
> +		compiler.hooks.emit.tap("appacache-webpack-plugin", (compilation) => {
Let's change the plugin name to `'AppCachePlugin'`.

2018-04-03 19:36 UTC, lettertwo commented on src/index.js
> -    compiler.plugin('emit', (compilation, callback) => {
I'd like to maintain backwards compatibility here, if possible. For instance, we could detect whether `compiler.hooks.emit.tap` is available, but fall back to `compiler.plugin` if it isn't.

2018-04-13 00:42 UTC, ccorcos commented
hey @lettertwo I addressed your comments

2018-04-16 17:57 UTC, ccorcos commented
ping @lettertwo

2018-05-11 10:00 UTC, briandipalma commented
Is this OK to merge?

2018-05-12 18:45 UTC, merged

2018-05-12 18:46 UTC, lettertwo commented
Sorry for the delay, everyone. I've merged this PR, but some tests are failing, and there are some linting nits i'm going to clean up before i cut a release.

Thanks for the PR @ccorcos!

2018-05-12 19:29 UTC, lettertwo commented
This is now published as [v1.4.0](https://www.npmjs.com/package/appcache-webpack-plugin/v/1.4.0). Thanks again for your PR and patience!

2018-05-14 21:22 UTC, briandipalma commented
Cheers, thank you.